name: country_code
description: Provides list of ISO 3166-1 coutry codes in enum-like class
version: 0.1.1
author: Denis Portnov <denixport@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
