name: country
description: ISO 3166-1 Coutry codes
version: 0.1.0
author: Denis Portnov <denixport@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
